### ISSUE TITLE
How would one implement code for servers?

### ISSUE THREAD

**Issue by Gammer0909** [MrScautHD/Sparkle#12]
In the README, it mentions that you could build games for a server (Eg. a multiplayer game) because you do not need the `Draw` command. However, I was wondering how you would have to implement this, as I am new to this library. 

Thanks, Gammer0909

**Comment by MrScautHD** [comment]
Hello!
We have removed the old system, and adding a better one is at the top of our to-do list (https://github.com/MrScautHD/Sparkle/issues/10).

**Comment by Gammer0909** [comment]
Ah, thanks!
