### ISSUE TITLE
Documentation uses things that aren't released yet

### ISSUE THREAD

**Issue by Gammer0909** [MrScautHD/Sparkle#15]
I'm following the documentation wiki to figure out how to use this library, however all of the things in the "Building a basic Game" script provided are set in 2.0.1, which is not currently released.

Thanks, Gammer0909

**Comment by MrScautHD** [comment]
Well yea the names not 100% the same but i not really wanna do the documentation  2 times...

**Comment by MrScautHD** [comment]
I hope you can understand that, if you need help join our dc server:  https://discord.gg/7XKw6YQa76
