### ISSUE TITLE
🧊 [Feature] Impliment MSBuild for `Headless` support.

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#9]
MSBuild (https://github.com/dotnet/msbuild)
======
MSBuild impliments a dynamic build system!

Get just compiled if client side (HEADED):
![Headed](https://github.com/MrScautHD/Sparkle/assets/65916181/7571ff80-67cc-412d-8767-27a7832b36c8)

Get just compiled if server side (HEADLESS):
![headless](https://github.com/MrScautHD/Sparkle/assets/65916181/d09c7798-e943-4b38-b53e-fe41b6465b93)

Works even in the middle of the script:
![if](https://github.com/MrScautHD/Sparkle/assets/65916181/df31f8a7-b9e5-4857-8409-748430b2e458)

**Comment by Gammer0909** [comment]
Wait, we can make macros in C#?

**Comment by MrScautHD** [comment]
Its called Attributes but yea :D

**Comment by Gammer0909** [comment]
Yay, less work!
